version: "3.7"

services:
  
  localstack:
    image: localstack/localstack-full:${LOCALSTACK_VERSION}
    container_name: "${LOCALSTACK_CONTAINER_NAME}"
    hostname: "${LOCALSTACK_CONTAINER_NAME}"
    ports:
      - "4566:4566"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      SERVICES: ${LOCALSTACK_SERVICES}
      DEBUG: ${LOCALSTACK_DEBUG}
      DATA_DIR: ${LOCALSTACK_DATA_DIR}
      DOCKER_HOST: unix:///var/run/docker.sock
      DEFAULT_REGION: ${LOCALSTACK_AWS_REGION}
      LGC_DEV: "TRUE"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../dynamodb:/tmp/dbscripts
      - ./../.localstack/init:/docker-entrypoint-initaws.d


  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin"
    container_name: "dynamodb-admin"
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://${LOCALSTACK_CONTAINER_NAME}:4566"
      AWS_REGION: ${LOCALSTACK_AWS_REGION}